apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-plugin-config
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: terraform-plugin
    spec:
      version: v1.0
      generate:
        command:
        - sh
        - c
        args:
        - |
          -r '.db_instance_endpoint.value | split(":")[0]' < terraform-output.json
      discover:
        fileName: "./terraform-output.json"
