apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: terraform-plugin
    spec:
      version: v1.0
      generate:
        command:
        - sh
        - c
        args:
        - |
          export ENDPOINT=$(jq -r '.db_instance_endpoint.value | split(":")[0]' < terraform-output.json | tr -d '\n' | base64) && \
          kubectl patch secret mysql-creds -p '{"data":{"host":"$ENDPOINT"}}' && \
          kubectl get secret mysql-creds -o yaml
      discover:
        fileName: "./terraform-output.json"
