name: Deploy AWS RDS Instance

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Deploy RDS to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 # Specify the Terraform version you are using

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
            TF_VAR_db_username: ${{ secrets.DATABASE_USERNAME }}
            TF_VAR_db_password: ${{ secrets.DATABASE_PASSWORD }}

      - name: Save Terraform Output
        run: terraform output -json > terraform-output.json

      - name: Upload Terraform Output as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-output
          path: terraform-output.json
